name: Convert to JSON and Fetch Database

on:
  schedule:
    - cron: '30 6 * * *' # Every day at 06:30 UTC (13:30 WIB)
  workflow_dispatch:

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Fetch latest database
      run: |
        curl -L https://github.com/yuldan14/predRice/raw/main/data_harga.db -o ./app/data_harga.db

    - name: Run conversion script
      run: |
        python ./app/convert_to_json.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./app/data_harga.json
        git commit -m "Update JSON data from database [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
